AllCops:
  Exclude:
    - memfs.gemspec
    - 'spec/**/*'
  TargetRubyVersion: 2.7

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - Rakefile
  Max: 90

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Lint/AmbiguousRegexpLiteral:
#   Enabled: false

# Lint/RescueException:
#   Enabled: false

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 10

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

Security/Open:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

# Style/FrozenStringLiteralComment:
#   Enabled: false

# Style/MultilineBlockChain:
#   Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/SignalException:
  EnforcedStyle: semantic

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
