AllCops:
  Exclude:
  - lib/fileutils.rb

AlignParameters:
  Enabled: false

BlockDelimiters:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

EmptyLinesAroundClassBody:
  Exclude:
  - lib/memfs/fake/file/content.rb

IfUnlessModifier:
  Enabled: false

IndentHash:
  EnforcedStyle: consistent

LineLength:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'

SpecialGlobalVars:
  Enabled: false

RegexpLiteral:
  Enabled: false

TrivialAccessors:
  Enabled: false
